Repository containers/toolbox, pull requests merged in 2020-08, with the labels that each got.

#524 cmd/initContainer: Mount a tmpfs at /tmp to match the host
  src/cmd/initContainer.go
Labels: bugfix, enhancement, minor change

#485 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#511 meson: Add option for installing tests
  meson.build
Labels: enhancement, minor change

#460 cmd/initContainer: Reinforce symlink redirection
  src/cmd/initContainer.go
Labels: bugfix, enhancement, major change
