Repository containers/toolbox, pull requests merged in 2020-07, with the labels that each got.

#498 cmd/create: Restore the spinner, when pulling an image, to stdout
  src/cmd/create.go
Labels: bugfix

#494 cmd/list: Re-enable highlighting of running containers
  src/cmd/list.go
Labels: enhancement, minor

#493 cmd/create: Update hint after creating a container
  src/cmd/create.go
Labels: bugfix, minor
