Repository containers/toolbox, pull requests merged in 2020-10, with the labels that each got.

#556 cmd/initContainer: Remove path on redirection when it exists
  src/cmd/initContainer.go
Labels: bugfix, minor change

#491 cmd/initContainer: Give access to the udev database
  src/cmd/initContainer.go
Labels: enhancement

#574 playbooks: Bump fedora-toolbox image to f34 for Rawhide
  playbooks/fedora-rawhide/pre-common.yaml
Labels: CI

#567 test/system: Test that toolboxes start alright
  test/system/201-run.bats
Labels: CI

#571 Fix warning for Ubuntu containers: "Error: terminfo entry not found for xterm-256color"
  profile.d/toolbox.sh
Labels: bugfix, minor change

#548 cmd/initContainer: Enable running minikube on Silverblue
  src/cmd/initContainer.go
Labels: enhancement, minor change

#594 test/system: Rework check if toolbox started successfully
  test/system/201-run.bats
  test/system/helpers.bash
Labels: CI, bugfix
