Repository containers/toolbox, pull requests merged in 2021-06, with the labels that each got.

#782 list: Fix typo
  src/cmd/list.go
Labels: 2. Host Realm, 3. Bugfix

#793 test/system: Fix variable dereference
  test/system/libs/helpers.bash
Labels: 2. Testing, 3. Bugfix, 6. Minor Change

#795 playbooks/setup-env: Show versions of more packages
  playbooks/setup-env.yaml
Labels: 2. CI, 2. Testing, 3. Enhancement, 6. Minor Change

#794 README.md, cmd/initContainer: Don't require /etc/machine-id in images
  README.md
  src/cmd/initContainer.go
Labels: 2. Container Configuration, 2. Container Realm, 3. Enhancement, 6. Minor Change

#799 cmd/list: Style fixes
  src/cmd/list.go
Labels: 2. Under The Hood, 3. Refinement

#800 cmd/list: Support images without names
  src/cmd/list.go
  test/system/102-list.bats
Labels: 2. Under The Hood, 3. Bugfix, 6. Minor Change

#806 completion/bash: Completely drop flag --very-verbose
  completion/bash/toolbox
Labels: 2. CLI, 3. Refinement, 6. Minor Change

#807 cmd/initContainer: Don't ignore unknown flags, yet
  src/cmd/initContainer.go
Labels: 2. CLI, 3. Refinement, 6. Minor Change

#812 test/system: Test the handling of unknown flags with each command
  test/system/002-help.bats
Labels: 2. Testing

#811 cmd/root: Wire root command to 'enter' command
  src/cmd/root.go
  test/system/002-help.bats
Labels: 2. CLI, 3. New Feature, 6. Major Change
