Repository containers/toolbox, pull requests merged in 2021-12, with the labels that each got.

#943 pkg/shell: Simplify code flow
  src/pkg/shell/shell.go
Labels: 6. Minor Change, 3. Refinement, 2. Under The Hood

#945 initContainer: Include execution error in message
  src/cmd/initContainer.go
Labels: 3. Refinement, 2. Under The Hood

#939 CONTRIBUTING: Content update & fixes
  CONTRIBUTING.md
Labels: 2. Documentation

#899 test/system: Test startup on Rawhide with supported versions
  .zuul.yaml
  test/system/000-setup.bats
  test/system/103-container.bats
  test/system/libs/helpers.bash
Labels: 3. Enhancement, 2. Testing

#510 cmd/create: Drop redundant label when creating a container
  src/cmd/create.go
Labels: 3. Enhancement, 6. Minor Change, 2. Host Realm, 2. Under The Hood

#949 README.md: Shorten it by linking to the website wherever possible
  README.md
Labels: 2. Documentation

#942 build: Drop the use of patchelf(1)
  meson.build
  playbooks/setup-env.yaml
  src/go-build-wrapper
  src/meson.build
Labels: 3. Enhancement, 6. Major Change, 2. Build System

#948 zuul: Run tests only for relevant files
  .zuul.yaml
Labels: 3. Enhancement, 2. CI
