Repository containers/toolbox, pull requests merged in 2021-05, with the labels that each got.

#720 Update bash completion
  completion/bash/toolbox
Labels: 2. CLI, 3. Enhancement, 6. Minor Change, Project Pickle 🥒

#715 README: /etc/machine-id is required
  README.md
Labels: 2. Documentation, 3. Bugfix

#757 Rename Dockerfile to Containerfile
  images/fedora/f28/Containerfile
  images/fedora/f29/Containerfile
  images/fedora/f30/Containerfile
  images/fedora/f31/Containerfile
  images/fedora/f32/Containerfile
  images/fedora/f33/Containerfile
  images/fedora/f34/Containerfile
Labels: 2. Images, 3. Refinement, 6. Minor Change

#565 cmd/run: Use home folder when $PWD is not in toolbox
  src/cmd/run.go
Labels: 2. Container Realm, 3. Enhancement, 6. Minor Change

#512 doc: Match man pages with Go Toolbox and extend them
  doc/toolbox-create.1.md
  doc/toolbox-enter.1.md
  doc/toolbox-help.1.md
  doc/toolbox-init-container.1.md
  doc/toolbox-list.1.md
  doc/toolbox-rm.1.md
  doc/toolbox-rmi.1.md
  doc/toolbox-run.1.md
  doc/toolbox.1.md
Labels: 2. Documentation

#469 Simplify container & image fetching using labels
  src/cmd/list.go
Labels: 3. Enhancement, 6. Major Change

#777 test/system: Use env var for invoking Toolbox
  test/system/001-version.bats
  test/system/002-help.bats
  test/system/101-create.bats
  test/system/102-list.bats
  test/system/103-run.bats
  test/system/104-rm.bats
  test/system/105-rmi.bats
Labels: 2. Testing, 3. Bugfix, 6. Minor Change

#779 ci: Drop testing on Fedora 32
  .zuul.yaml
Labels: 2. CI, 2. Testing

#780 test/system: Bump secondary fedora image from 29 to 32
  playbooks/setup-env.yaml
  profile.d/toolbox.sh
  test/system/101-create.bats
  test/system/102-list.bats
  test/system/libs/helpers.bash
Labels: 2. Testing, 3. Refinement, 6. Minor Change

#774 test/system: Decouple image caching from Zuul
  playbooks/setup-env.yaml
  test/system/000-setup.bats
  test/system/101-create.bats
  test/system/102-list.bats
  test/system/999-teardown.bats
  test/system/libs/helpers.bash
Labels: 2. CI, 2. Testing, 3. Enhancement, 6. Major Change

#776 cmd/list: Recognize UBI images
  src/cmd/list.go
  test/system/000-setup.bats
  test/system/102-list.bats
  test/system/libs/helpers.bash
Labels: 2. Host Realm, 3. Bugfix, 6. Minor Change
