Repository containers/toolbox, pull requests merged in 2021-03, with the labels that each got.

#554 pkg/utils: Drop length check when getting mount options
  src/pkg/utils/utils.go
Labels: 2. Host Realm, 3. Bugfix

#712 src/create: Handle read-only /boot
  src/cmd/create.go
Labels: 2. Container Configuration, 3. Bugfix, 6. Minor Change, 6. Requires Toolbox Recreation

#711 .github: Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: 3. Bugfix

#723 images: Use a regular file, not a symbolic link, for README.md
  images/fedora/f32/README.md
  images/fedora/f33/README.md
  images/fedora/f34/README.md
Labels: 2. Documentation, 3. Bugfix

#727 cmd/create: Start spinner earlier
  src/cmd/create.go
Labels: 2. CLI, 3. Refinement

#726 cmd/create: Cleanup entry-point command assembly
  src/cmd/create.go
Labels: 2. Container Configuration, 3. Refinement, 6. Minor Change, 6. Requires Toolbox Recreation

#474 [unit test] Add cmd/pkg/shell
  src/go.mod
  src/go.sum
  src/pkg/shell/shell_test.go
Labels: 2. Testing, 3. Enhancement

#729 pkg/utils: Add missing variable in fmt.Errorf
  src/pkg/utils/utils.go
Labels: 3. Bugfix

#724 cmd/initContainer: Ignore unknown flags
  src/cmd/initContainer.go
Labels: 2. CLI, 3. Bugfix, 6. Minor Change

#730 Connect Go unit tests to Meson & rename CI job
  .zuul.yaml
  playbooks/unit-test.yaml
  src/meson.build
Labels: 2. CI, 3. Enhancement

#731 playbooks: Properly separate builddir setup & build
  playbooks/system-test.yaml
  playbooks/unit-test.yaml
Labels: 2. CI, 3. Refinement

#733 build: Drop ShellCheck on Shell Toolbox
  meson.build
Labels: 2. Build System, 3. Refinement, 6. Minor Change

#728 cmd: Properly wrap around errors
  src/cmd/create.go
  src/cmd/list.go
  src/cmd/rm.go
  src/cmd/rmi.go
  src/cmd/root.go
Labels: 2. CLI, 3. Refinement, 6. Minor Change

#736 cmd/list: Rename functions for getting images/containers
  src/cmd/list.go
  src/cmd/run.go
Labels: 3. Refinement, 6. Minor Change

#737 cmd/rm,rmi: Use function for getting list of images/containers
  src/cmd/rm.go
  src/cmd/rmi.go
Labels: 3. Refinement, 6. Minor Change

#735 cmd/root: Streamline preRun of CLI root
  src/cmd/root.go
Labels: 2. CLI, 3. Refinement, 6. Minor Change

#738 cmd/rm,rmi: Properly rename called function
  src/cmd/rm.go
  src/cmd/rmi.go
Labels: 3. Bugfix

#739 utils: bump Fedora fallback version to 33
  src/pkg/utils/utils.go
Labels: 3. Enhancement

#725 playbooks/system-test: Show test execution time
  playbooks/system-test.yaml
Labels: 2. CI, 3. Enhancement, 6. Minor Change
