Repository containers/toolbox, pull requests merged in 2021-02, with the labels that each got.

#690 Make use of dynamic CI status badge
  README.md
Labels: documentation

#693 test/system: Refactor tests using bats-support and bats-assert
  .gitignore
  playbooks/fedora-31/setup-env.yaml
  playbooks/fedora-32/setup-env.yaml
  playbooks/fedora-33/setup-env.yaml
  playbooks/fedora-rawhide/setup-env.yaml
  test/system/001-version.bats
  test/system/002-help.bats
  test/system/101-create.bats
  test/system/101-list.bats
  test/system/102-create.bats
  test/system/102-list.bats
  test/system/103-list.bats
  test/system/103-run.bats
  test/system/104-rm.bats
  test/system/105-rmi.bats
  test/system/201-run.bats
  test/system/301-rm.bats
  test/system/302-rmi.bats
  test/system/README.md
  test/system/helpers.bash
  test/system/libs/helpers.bash
Labels: CI, enhancement, major change

#695 ci: Drop testing on Fedora 31
  .zuul.yaml
  playbooks/fedora-31/setup-env.yaml
  playbooks/fedora-31/system-test-fedora-31.yaml
Labels: CI

#697 ci: Fix pulled image name
  playbooks/fedora-34/setup-env.yaml
Labels: CI

#694 playbooks: Show Podman info necessary for filing issues
  playbooks/fedora-32/setup-env.yaml
  playbooks/fedora-33/setup-env.yaml
  playbooks/fedora-34/setup-env.yaml
  playbooks/fedora-rawhide/setup-env.yaml
Labels: CI

#700 test/system/README.md: Update the URLs for bats-assert and bats-support
  test/system/README.md
Labels: 2. Documentation

#615 src/cmd, playbooks: Drop image prefix for fedora-toolbox
  images/fedora/f32/Dockerfile
  images/fedora/f33/Dockerfile
  images/fedora/f34/Dockerfile
  playbooks/fedora-32/setup-env.yaml
  playbooks/fedora-33/setup-env.yaml
  playbooks/fedora-34/setup-env.yaml
  playbooks/fedora-rawhide/setup-env.yaml
  src/pkg/utils/utils.go
  test/system/101-create.bats
  test/system/102-list.bats
  test/system/libs/helpers.bash
Labels: 6. Major Change

#676 Check if /mnt exists before adding it as a volume mount
  src/cmd/create.go
Labels: 2. Container Realm, 3. Bugfix
