Repository containers/toolbox, pull requests merged in 2021-11, with the labels that each got.

#913 cmd/enter: Don't use double negation
  src/cmd/enter.go
  src/cmd/run.go
Labels: 6. Minor Change, 3. Refinement, 2. Under The Hood

#819 pkg/utils: Move cmd utility functions to cmd
  src/cmd/create.go
  src/cmd/enter.go
  src/cmd/help.go
  src/cmd/initContainer.go
  src/cmd/list.go
  src/cmd/rm.go
  src/cmd/rmi.go
  src/cmd/root.go
  src/cmd/run.go
  src/cmd/utils.go
  src/meson.build
  src/pkg/utils/utils.go
Labels: 6. Minor Change, 3. Refinement, 2. Under The Hood

#907 Mount Smart Card Daemon socket (pcsd) inside the toolbox container
  src/cmd/create.go
Labels: 6. Minor Change, 3. New Feature, 2. Container Configuration, 6. Requires Toolbox Recreation

#881 Make welcome message appear on Fedora Kinoite
  profile.d/toolbox.sh
Labels: 3. Enhancement, 2. Documentation, 2. Host Realm

#924 cmd/utils: Add copyright and license notices
  src/cmd/utils.go
Labels: 3. Bugfix, 2. Documentation

#640 cmd/initContainer: Avoid RPM failures due to unexpected file owners
  src/cmd/initContainer.go
Labels: 6. Minor Change, 3. Bugfix, 2. Container Realm

#930 Add capsh as a container requirement in the docs
  README.md
Labels: 3. Bugfix, 2. Documentation

#927 zuul: pump the current fedora releases to 34 & 35
  .zuul.yaml
Labels: 3. Enhancement, 6. Minor Change, 2. CI
