Repository containers/toolbox, pull requests merged in 2021-07, with the labels that each got.

#824 test/system: Update README
  test/system/README.md
Labels: 2. Documentation, 2. Testing, 3. Refinement, 6. Minor Change

#834 playbooks/setup-env: Show version of glibc
  playbooks/setup-env.yaml
Labels: 2. CI, 3. Enhancement

#833 pkg/utils: Drop redundant functions
  src/pkg/utils/utils.go
Labels: 2. Under The Hood, 3. Refinement, 6. Minor Change

#314 Install iproute package in toolbox images
  images/fedora/f33/extra-packages
  images/fedora/f34/extra-packages
  images/fedora/f35/extra-packages
Labels: 2. Images

#827 cmd/create: Mount whole host instead of its subsets
  src/cmd/create.go
Labels: 2. Container Configuration, 3. Enhancement, 6. Major Change, 6. Requires Toolbox Recreation

#841 pkg/utils: Test ParseRelease
  src/pkg/utils/utils_test.go
Labels: 2. Testing, 3. Enhancement

#835 pkg/utils: Rename parameter in ParseRelease
  src/pkg/utils/utils.go
Labels: 2. Under The Hood, 3. Refinement, 6. Minor Change

#846 test/system: Adjust asserts for broken test
  test/system/102-list.bats
Labels: 2. Testing, 3. Bugfix

#831 tests: Added a verbose test for container starting
  test/system/103-container.bats
  test/system/104-run.bats
  test/system/105-rm.bats
  test/system/106-rmi.bats
Labels: 2. Testing, 3. Enhancement

#847 pkg/utils: Streamline functions
  src/pkg/utils/utils.go
Labels: 2. Under The Hood, 3. Refinement, 6. Minor Change

#843 test/system: Minor fixes
  test/system/104-run.bats
Labels: 2. Testing, 3. Refinement, 6. Minor Change

#845 utils: bump the fallback Fedora version to 34
  src/pkg/utils/utils.go
Labels: 2. Under The Hood, 3. Enhancement

#844 test/system: Fix flaky test
  test/system/104-run.bats
Labels: 2. Testing, 3. Bugfix, 6. Minor Change

#850 test/system: Use BATS_RUN_TMPDIR for image cache
  test/system/libs/helpers.bash
Labels: 2. Testing, 3. Enhancement, 6. Minor Change

#854 test/system: Test pull failure
  test/system/101-create.bats
Labels: 2. Testing, 3. Enhancement, 6. Minor Change
