Repository containers/toolbox, pull requests merged in 2022-01, with the labels that each got.

#964 .zuul: Try to prevent the CI from timing out on Fedora Rawhide
  .zuul.yaml
Labels: 3. Bugfix, 2. CI

#958 CONTRIBUTING: custom graphic
  CONTRIBUTING.md
  data/gfx/CONTRIBUTING.gif
  data/gfx/README.gif
  data/gfx/powerup.gif
Labels: 3. Enhancement, 2. Documentation

#974 ci: Add golangci linter
  .github/workflows/linting.yaml
Labels: 2. CI, 3. New Feature

#976 pkg/utils: Use new UBI toolbox image
  src/pkg/utils/utils.go
  test/system/libs/helpers.bash
Labels: 3. Enhancement, 6. Minor Change, 2. Under The Hood

#978 ci: Remove only-new-issues option from linter run
  .github/workflows/linting.yaml
Labels: 3. Bugfix, 2. CI

#979 cmd: Fix issues raised by Golangci
  src/cmd/create.go
  src/cmd/initContainer.go
  src/cmd/run.go
Labels: 3. Refinement, 2. Under The Hood

#973 ci: Build & Publish Fedora Toolbx images with GitHub Packages
  .github/workflows/image-factory.yaml
Labels: 2. Images, 2. CI, 3. New Feature

#981 ci: image machinery fix
  .github/workflows/image-factory.yaml
Labels: 3. Bugfix, 2. CI

#965 build: Call 'systemd-tmpfiles --create' when installing
  meson.build
  meson_post_install.py
  playbooks/setup-env.yaml
Labels: 3. Enhancement, 2. Build System
