Repository containers/toolbox, pull requests merged in 2023-12, with the labels that each got.

#1409 test/system: switch HOME fallback to tmp dir (fix for Ubuntu hosts)
  test/system/104-run.bats
Labels: 2. Testing

#1427 cmd/utils: Increase buffer size when discarding terminal input
  src/cmd/utils.go
Labels: 3. Bugfix, 2. CLI

#1428 cmd/create: Require valid terminal when prompting to pull an image
  src/cmd/create.go
  test/system/101-create.bats
Labels: 3. Enhancement, 2. CLI, 7. Needs tests
